version: '3.7'
services:
  kong:
    image: kong:2.8
    container_name: kong-9200
    restart: always
    environment:
      - TZ=Asia/Bangkok
      - KONG_DATABASE=off
      - KONG_ANONYMOUS_REPORTS=off
      - KONG_DECLARATIVE_CONFIG=/etc/kong/conf.d/kong.yml
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_LISTEN=0.0.0.0:80 reuseport backlog=65535, 0.0.0.0:443 ssl http2 reuseport backlog=65535
      - KONG_TRUSTED_IPS=0.0.0.0/0,::/0
      - KONG_REAL_IP_RECURSIVE=on
      - KONG_STATUS_LISTEN=127.0.0.1:9123
      - KONG_PROXY_ACCESS_LOG=/dev/null
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_HEADERS=off
      - KONG_LUA_SSL_TRUSTED_CERTIFICATE=/etc/ssl/certs/ca-certificates.crt
    command: kong start
    ports:
      - 9200:80
      - 8002:8001
    volumes:
      - ./conf.d:/etc/kong/conf.d

  opensearch-node:
    image: opensearchproject/opensearch:1.3.3
    container_name: opensearch-node
    restart: always
    hostname: opensearch-node
    environment:
      - cluster.name=opensearch-single
      - discovery.type=single-node
      - node.name=opensearch
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - network.host=0.0.0.0
      - compatibility.override_main_response_version=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - ./opensearch-data:/usr/share/opensearch/data
    ports:
      - 9201:9200
      - 9600:9600 # required for Performance Analyzer
    healthcheck:
      test: curl -sk -u admin:admin https://opensearch-node:9200/_cluster/health > /dev/null || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.3.3
    container_name: opensearch-dashboards
    restart: always
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node:9200"]' # must be a string with no spaces when specified as an environment variable
      OPENSEARCH_USERNAME: admin
      OPENSEARCH_PASSWORD: admin
      OPENSEARCH_SSL_VERIFICATIONMODE: none

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Bangkok
      - STORAGE_TYPE=elasticsearch
      - STORAGE_PORT_9200_TCP_ADDR="http://192.168.1.109"
      - ES_USERNAME=admin
      - ES_PASSWORD=admin
      - ES_SSL_NO_VERIFY=true
    command: --logging.level.zipkin2=DEBUG

  fluent-bit:
    image: fluent/fluent-bit:1.9
    container_name: fluent-bit
    restart: always
    network_mode: host
    volumes:
    - ./conf/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    - ./conf/parsers.conf:/fluent-bit/etc/parsers.conf
    - ./conf/filter.lua:/fluent-bit/etc/filter.lua
    - ./fluent-data:/data/db
